# Generated by Django 6.0.5 on 2026-06-02 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='quantidade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='A quantidade movimentada deve ser de pelo menos 1 unidade.')]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_estoque',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='A quantidade em estoque não pode ser negativa.')]),
        ),
    ]
